apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: TrainingPortal
metadata:
  name: lab-k8s-fundamentals
spec:
  portal:
    ingress:
      hostname: lab-k8s-fundamentals
    registration:
      type: anonymous
    reserved: 0
    sessions:
      maximum: 5
    updates:
      workshop: true
  workshops:
  - name: lab-k8s-fundamentals
    expires: 30m
    orphaned: 5m
