apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: lab-k8s-fundamentals
spec:
  title: Kubernetes Fundamentals
  description: An interactive workshop on Kubernetes fundamentals.
  session:
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
    namespaces:
      budget: small
    
